package by.htp.command;

public enum CommandName{
	NO_SUCH_COMMAND, DO_ANYTHING_COMMAND, LOGINATION, REGISTRATION, ADD_NEW_PATIENT,
	FIND_USER, FIND_PATIENT, MEDICATION, FIXING, USER_EDIT_PROFILE, FIND_PATIENT_FROM_USER,
	EDIT_MEDICATION, DEL_MEDICATION, ADD_MEDICATION, ALL_MEDICATION, UNFIXING, LIVE, ADD_PHOTO,
	DIAGNOSIS, RIGHT_OUT, OUT_OFF, BACK_USER_PAGE, USER_CHANGER,DISMISSAL, ADD_MEDICATION_PERIOD,
	MEDICATION_PEREOSITY, SHOW_ALL_USERS, USER_DISSMISAL_LIST, SHOW_ALL_PATIENTS, PATIENT_DISCHANGED_LIST, CHANGE; 
}																														
